version: '3.8'

name: 'utils-kehet-com'

services:

  nginx:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - NGINX_HOST=utils.kehet.com

networks:
  default:
    external: true
    name: scoobydoo
