import { defineStore } from "pinia";

export const useResistorStore = defineStore("resistor", {
  state: () => {
    return {
      selected: [0, 1, 0, 0, 0, 1, 0],
      bandCount: 3,
      rows: [
        {
          label: "Black",
          class: "bg-black text-white",
          col1: null,
          col2: "0",
          col3: "0",
          col4: "&times;10<sup>0</sup>",
          col5: null,
          col6: "&plusmn;250",
          multiplier: 0,
          tolerance: null,
        },
        {
          label: "Brown",
          class: "bg-amber-900 text-white",
          col1: "1",
          col2: "1",
          col3: "1",
          col4: "&times;10<sup>1</sup>",
          col5: "&plusmn;1%",
          col6: "&plusmn;100",
          multiplier: 1,
          tolerance: 1,
        },
        {
          label: "Red",
          class: "bg-red-600 text-white",
          col1: "2",
          col2: "2",
          col3: "2",
          col4: "&times;10<sup>2</sup>",
          col5: "&plusmn;2%",
          col6: "&plusmn;50",
          multiplier: 2,
          tolerance: 2,
        },
        {
          label: "Orange",
          class: "bg-orange-500 text-black",
          col1: "3",
          col2: "3",
          col3: "3",
          col4: "&times;10<sup>3</sup>",
          col5: "&plusmn;0.05%",
          col6: "&plusmn;15",
          multiplier: 3,
          tolerance: 0.05,
        },
        {
          label: "Yellow",
          class: "bg-yellow-500 text-black",
          col1: "4",
          col2: "4",
          col3: "4",
          col4: "&times;10<sup>4</sup>",
          col5: "&plusmn;0.02%",
          col6: "&plusmn;25",
          multiplier: 4,
          tolerance: 0.02,
        },
        {
          label: "Green",
          class: "bg-lime-600 text-black",
          col1: "5",
          col2: "5",
          col3: "5",
          col4: "&times;10<sup>5</sup>",
          col5: "&plusmn;0.5%",
          col6: "&plusmn;20",
          multiplier: 5,
          tolerance: 0.5,
        },
        {
          label: "Blue",
          class: "bg-blue-600 text-white",
          col1: "6",
          col2: "6",
          col3: "6",
          col4: "&times;10<sup>6</sup>",
          col5: "&plusmn;0.25%",
          col6: "&plusmn;10",
          multiplier: 6,
          tolerance: 0.25,
        },
        {
          label: "Violet",
          class: "bg-violet-800 text-white",
          col1: "7",
          col2: "7",
          col3: "7",
          col4: "&times;10<sup>7</sup>",
          col5: "&plusmn;0.1%",
          col6: "&plusmn;5",
          multiplier: 7,
          tolerance: 0.1,
        },
        {
          label: "Grey",
          class: "bg-gray-500 text-white",
          col1: "8",
          col2: "8",
          col3: "8",
          col4: "&times;10<sup>8</sup>",
          col5: "&plusmn;0.01%",
          col6: "&plusmn;1",
          multiplier: 8,
          tolerance: 0.01,
        },
        {
          label: "White",
          class: "bg-white text-black",
          col1: "9",
          col2: "9",
          col3: "9",
          col4: "&times;10<sup>9</sup>",
          col5: null,
          col6: null,
          multiplier: 9,
          tolerance: null,
        },
        {
          label: "Gold",
          class: "bg-amber-400 text-black",
          col1: null,
          col2: null,
          col3: null,
          col4: "&times;10<sup>-1</sup>",
          col5: "&plusmn;5%",
          col6: null,
          multiplier: -1,
          tolerance: 5,
        },
        {
          label: "Silver",
          class: "bg-neutral-400 text-black",
          col1: null,
          col2: null,
          col3: null,
          col4: "&times;10<sup>-2</sup>",
          col5: "&plusmn;10%",
          col6: null,
          multiplier: -2,
          tolerance: 10,
        },
        {
          label: "Pink",
          class: "bg-pink-500 text-black",
          col1: null,
          col2: null,
          col3: null,
          col4: "&times;10<sup>-3</sup>",
          col5: null,
          col6: null,
          multiplier: -3,
          tolerance: null,
        },
      ],
    };
  },
  persist: {
    enabled: true,
  },
});
